apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: kuma-java
deploy:
  kubectl:
    manifests:
      - kubernetes/meeting-deployment.yaml
      - kubernetes/work-deployment.yaml
      - kubernetes/ingress.yaml