apiVersion: kuma.io/v1alpha1
kind: VirtualOutbound
mesh: default
metadata:
  name: dot-mesh
spec:
  selectors:
    - match:
        kuma.io/service: "*"
  conf:
    host: "{{.service}}.mesh"
    port: "80"
    parameters:
      - name: service
        tagKey: "k8s.kuma.io/service-name"
      - name: dummy
        tagKey: "kuma.io/service"
